### ISSUE TITLE
Update Debian/Ubuntu pgbadger packages

### ISSUE THREAD

**Issue by jberkus** [dalibo/pgbadger#199]
... which are still at 3.3.  Clearly someone from the pgbadger project will need to take charge of these.

**Comment by darold** [comment]
Hi,

After asking several time per email and irc since months now, I'm afraid that the actual maintainer of the pgbadger package doesn't want to update or remove the package from the Debian repository. I don't know why he don't want to do that because it never answer.

If anyone at the Debian community can tell him all the evil that I think of him or better do something to remove this obsolete package from the official Debian repository. pgBadger is up-to-date on the pgdg Debian repository at apt.postgresql.org.

Sorry Josh but I'm not able to do anything on this part, anyway thanks for the report.

**Comment by cyril-bouthors** [comment]
I just uploaded 7.0 into Debian.

The Debian bug tracking system is reachable at http://bugs.debian.org/

**Comment by darold** [comment]
Oh thanks a lot Cyril, I'm glad that finally this issue can be closed and pgbadger Debian user may have a 2 years jump in the future. Thanks for this work.

**Comment by cyril-bouthors** [comment]
On Wed, May 13, 2015 at 7:00 PM, Darold <notifications@github.com> wrote:

> Oh thanks a lot Cyril, I'm glad that finally this issue can be closed and
> pgbadger Debian user may have a 2 years jump in the future. Thanks for this
> work.
>

Sorry about being so late.


-- 
Cyril Bouthors - go-managed.com <http://www.go-managed.com/> -
+33-184-161-617 +1-347-294-7146
https://www.linkedin.com/in/cyrilbouthors
