### ISSUE TITLE
html output changes

### ISSUE THREAD

**Issue by sebastianwebber** [dalibo/pgbadger#203]
Hi there,

I'm thinking about customize the html output to export all data into json files and load it using ajax requests trying to speed up the page loading.

There is any plans to do that? Can I start that change and propose a pull request?

Thanks!

**Comment by sebastianwebber** [comment]
@darold I want start this feature this week. Do you see any problem for using a external JS library like angular.js to dynamically load the data?

Regards,

**Comment by darold** [comment]
Hi,

Why an other javascript library? pgBadger is already including jquery, bootstrap and flotr2, that should be possible to perform dynamic data load with some of them, no?

Regards,

**Comment by sebastianwebber** [comment]
Hi @darold ,

Indeed its possible use jquery to load the external json data. But my proposal it's more than that.

Now, a empty report file contains more than 72k of html code (excluding the css and the js files). With the data can reach many megabytes. Files larger than 100mb become difficult to open a browser like google chrome. I believe it is possible to create much larger files with logs of several weeks or months.

My idea is create a new ui, breaking that interface in many tiny files, loaded only if needed. For that, angular.js sounds like a good idea.

I created a small app to work like pgtune, that uses angular to generate the html content. All data is read from a json file, like i suggested. Perhaps you can see the source code to get a better idea that i talked about. the project URL is www.pgconfig.org .

what do you think about that?

Regards,

**Comment by darold** [comment]
Hi,

The objective of pgBadger is to be a standalone log analyzer that just need Perl to report all information in a single html file. There is a reason for that: no other package or program installation and a report easy to send to a support or development team. If you have hundred of megabytes of report this is because you are using the wrong option. A pgBadger report with size above 10MB is not really usable. Normally a weekly log of 20GB or more should  produce a report around 5MB. If this is not the case, maybe you are storing too many top queries or your queries are really too long. In both case this can be controlled by command line option.

I don't really see any interest of doing what you want to do with pgBadger outside having a dynamic rendering of the interface, which can be a good thing if we can keep the all in one HTML file philosophy and that the use of external json data file is an option like others. In this case we can also use the angular.js library, but remember that if you are doing that for being able to load megabytes of data, you will have the same problem at the end. Being able to dynamically apply filters on the data is more interesting.

Best regards,
