### ISSUE TITLE
pgbadger reads 0 queries from my log file

### ISSUE THREAD

**Issue by mbecroft** [dalibo/pgbadger#227]
I can't get pgbadger to work at all on my log files. I've tried several different log_line_prefix options, including none, and both (log_min_duration_statement = 0) and (log_statement='ddl', log_duration = on with pgbadger --log-duration) but in all cases I get the output:

Parsed  n bytes of n (100.00%), queries: 0, events: 0

By way of example, my current postgresql.conf is:

log_line_prefix = '%t [%p-%l] %q%u@%d [%a] '
log_min_duration_statement = 0

and I run pgbadger (master cloned from git today) on some test log data file (pg-log-example) as follows:

$ pgbadger --prefix '%t [%p-%l] %q%u@%d [%a]' pg-log-example
[========================>] Parsed 11740 bytes of 11740 (100.00%), queries: 0, events: 0
LOG: Ok, generating html report...

I will attempt to attach pg-log-example, which is representative of my overall logs, to this ticket.

I suspect the problem is that pgbadger does not like my log_line_prefix/--prefix, but I'm not sure where the problem could be.

**Comment by mbecroft** [comment]
pg-log-example: http://pastebin.com/pG1FeCci

**Comment by darold** [comment]
pgBadger like all logs provide that they respect the mandatories fields in the log_line_prefix. Here all placeholders are present but the problem comes from an extra placeholder %q, pgBadger do not recognize it. If you removed it from the --prefix option this will works.

I will see how to handle that autoatically in pgBadger.

Regards,

**Comment by darold** [comment]
Commit b7b5f74 remove automatically the %q placeholder from the --prefix option value.
