### ISSUE TITLE
No more graphs after upgrading to 7.2 (and then 7.3)

### ISSUE THREAD

**Issue by lentferj** [dalibo/pgbadger#260]
We upgraded our pgBadger to 7.2 last week. After that we could no see any graphs in the reports anymore. We then updated to 7.3 because we thought it might fix the problem - but it didn't - still no graphs in the reports. The rest of the reports look good - everything is there, just the graphs are missing.

We run pgBadger like this (example):
/usr/bin/pgbadger -f stderr -q -x html -U nagios -U postgres  -I /srv/www/vhosts/pgbadger/logs/pp-pg-dev/postgresql-2016-01-18_000000.log -X -o /srv/www/vhosts/pgbadger/htdocs/pp-pg-dev-inc

So, incremental and extra-files mode.

Any idea?

Also: how can I force pgBadger to recreate the reports for a specific day/week if run in incremental mode?

**Comment by darold** [comment]
It's because the ressources files have not been updated, what you need to do is remove old files front the output directory and run pgbadger again with the -X. Saying that will not solves the problem of old html report that need the old javascript library, I'm sorry for that I had to warn for this potential issue in release note.

If you have preserved the binary files in your report directory I have just committed a patch (3aa8379) that add the --rebuild option to be able to rebuild all html reports in an incremental output directory where there is binary data files. If there's no binary file because you have used the retention option (-R | --retention) pgbadger will keep the original report untouched. 

Please download latest development code from github and proceed as follow:
``` 
rm /srv/www/vhosts/pgbadger/htdocs/*.js
rm/srv/www/vhosts/pgbadger/htdocs/*.css
pgbadger -X -I -O /srv/www/vhosts/pgbadger/htdocs/ --rebuild
``` 
This can take a very long time following the number of reports.

Latest development code can be obtained using:

    wget https://github.com/dalibo/pgbadger/archive/master.zip

Let me know.

**Comment by lentferj** [comment]
It worked - for those where we still had the bin files. At first we tought it didn't work until we figured out we were looking at a DEV machine and first week of 2016 (no traffic at all :) ).
For those days where we did not have any bin files anymore it worked in that way that it did not touch anything - so we still didn't have graphs for those ("RefernceError: Flotr ist no defined").
Anyway, as we still have the original Postgres log files around we decided do just rebuild the last 3 month from logs completly.
