### ISSUE TITLE
Total connections per day

### ISSUE THREAD

**Issue by atlantapeter** [dalibo/pgbadger#286]
Hi,

I recently started using pgbadger monitoring tool for my postgre database. Here, how can I see the total number of connections per day as I am not able to find it in the pgbadger.

Thanks in advance,
Pete

**Comment by darold** [comment]
Hi Pete,

This information is available from the "Global Stats" menu and the "Connections" tab.

Regards,

**Comment by atlantapeter** [comment]
![capture](https://cloud.githubusercontent.com/assets/20225965/16522189/1b849246-3f6a-11e6-9e1e-efce250e1c3d.PNG)

Thanks for the reply. Is this what you were mentioning about. I think they are total number of connection so far. But here, I am trying to find the 'total number of connections per day'.

**Comment by darold** [comment]
This is the number of connections detected in your log, if you have a daily rotated log it is the connections per day. Otherwise there is no such information. I don't know what you want to do with this metric but the number of connections per day is not really useful, the number of connections and simultaneous sessions per seconds are more interesting.
