### ISSUE TITLE
slowest queries are presented with some other query's text

### ISSUE THREAD

**Issue by ericcj** [dalibo/pgbadger#324]
i'm running pgbadger with all the same options in my last issue https://github.com/dalibo/pgbadger/issues/316  (thanks for your help!)

i noticed this a while ago and was confused that "SELECT 1" was taking a long time, but i happened to dig into the log this time and that's not the correct query text at all:

 Slowest individual queries

Rank	Duration	Query
1	3s511ms	
SELECT 1;
[ Date: 2017-01-11 20:34:54 - Database: foo - User: bar - Remote: 10.0.0.8 ]
2	3s458ms	
SELECT 1;
[ Date: 2017-01-11 20:43:43 - Database: foo - User: bar - Remote: 10.0.1.155 ]

2017-01-11 20:34:51 UTC:10.0.0.8(49636):bar@foo:[39592]:LOG: execute <unnamed>: SELECT "assets". FROM "assets" WHERE "assets"."local_identifier" = 'baz' LIMIT 1 /line:/app/models/concerns/pushd_model.rb:192:in `rescue in block in create_or_update_batch!'*/
2017-01-11 20:34:54 UTC:10.0.0.8(49636):bar@foo:[39592]:LOG: duration: 3511.178 ms

however, the 3rd slowest query, that takes < 1s has its own correct query text.  any ideas?

**Comment by darold** [comment]
When log_duration and log_statement are activated in postgresql.conf, pgbadger associate the duration found to the previous statement in the log. The problem is that log_duration and log_statement log entries can appears with some other log entries between them so using this method can associate duration to the wrong queries.

This is why it is recommended in the pgbadger documentation to disable log_duration and log_statement and use log_min_duration_statement.
